// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertiesListings.DataContext;

#nullable disable

namespace PropertiesListings.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220627102937_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PropertiesListings.Models.City", b =>
                {
                    b.Property<int>("cityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("cityName")
                        .HasColumnType("longtext");

                    b.Property<int>("population")
                        .HasColumnType("int");

                    b.HasKey("cityId");

                    b.ToTable("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
